 /*
  * This file was generated by the devil.
  * Please do not edit it directly or you will go to hell
  */

#ifndef _CONFIG_H_
#define _CONFIG_H_

# define TARGET_ARCH i386
# define TARGET_REPO i386
# define i386

#endif /* _CONFIG_H_ */

